// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    LineItemTable: typeof import('./src/components/LineItemTable.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
  }
}

export {}
