// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BillTypePicker: typeof import('./src/components/workorder/pickers/BillTypePicker.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    ClientPicker: typeof import('./src/components/workorder/pickers/ClientPicker.vue')['default']
    ContactPicker: typeof import('./src/components/workorder/pickers/ContactPicker.vue')['default']
    Copy: typeof import('./src/components/ui/Copy.vue')['default']
    DarkSwitcher: typeof import('./src/components/ui/DarkSwitcher.vue')['default']
    Datalist: typeof import('./src/components/ui/Datalist.vue')['default']
    DatePicker: typeof import('./src/components/ui/DatePicker.vue')['default']
    Divider: typeof import('./src/components/ui/Divider.vue')['default']
    Editor: typeof import('./src/components/Editor/Editor.vue')['default']
    EditTask: typeof import('./src/components/workorder/Task/EditTask.vue')['default']
    EmployeePicker: typeof import('./src/components/workorder/pickers/EmployeePicker.vue')['default']
    Filter: typeof import('./src/components/search/Filter.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    Job: typeof import('./src/components/workorder/Job.vue')['default']
    JobPicker: typeof import('./src/components/workorder/pickers/JobPicker.vue')['default']
    JobTypePicker: typeof import('./src/components/workorder/pickers/JobTypePicker.vue')['default']
    Nav: typeof import('./src/components/Nav/Nav.vue')['default']
    NavItem: typeof import('./src/components/Nav/NavItem.vue')['default']
    PrintPage: typeof import('./src/components/print/PrintPage.vue')['default']
    ProjectInfo: typeof import('./src/components/workorder/ProjectInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/Search.vue')['default']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    Sort: typeof import('./src/components/search/Sort.vue')['default']
    StatusIndicator: typeof import('./src/components/ui/StatusIndicator.vue')['default']
    StatusPicker: typeof import('./src/components/workorder/pickers/StatusPicker.vue')['default']
    TaskItem: typeof import('./src/components/workorder/Task/TaskItem.vue')['default']
    Tasks: typeof import('./src/components/workorder/Task/Tasks.vue')['default']
    Workorder: typeof import('./src/components/workorder/Workorder.vue')['default']
    WorkorderInfo: typeof import('./src/components/workorder/WorkorderInfo.vue')['default']
  }
}

export {}
