import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetUno,
  presetWebFonts,
  // transformerDirectives,
  // transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: {
    'bg-base': 'bg-bg-lit-c dark:bg-bg-drk-g',
    'bg-1': 'bg-bg-lit-a dark:bg-bg-drk-f',
    'bg-2': 'bg-bg-lit-b dark:bg-bg-drk-f',
    'bg-3': 'bg-fg-lit-norm dark:bg-fg-drk-norm/5',
    'border-base': 'border-fg-lit-norm dark:border-none border-1',
    'btn': 'p2 rounded shadow-md cursor-pointer disabled:cursor-default disabled:opacity-50 text-h5',
    'btn-active': 'btn-primary op100',
    'btn-primary': 'bg-bg-lit-a dark:bg-bg-drk-f',
    'btn-toggle': 'btn-primary op70',
    'btn-inactive': 'btn-primary op40',
    'btn-icon': 'op70 group-hover:op100 in_out',
    'icon-btn': 'op60 hover:op100 in_out',
    'in_out': 'transition duration-300 ease-in-out',
    'input-base': 'bg-bg-lit-a  dark:bg-bg-drk-k',
    'highlight': 'bg-fg-lit-norm dark:bg-fg-drk-muted text-fg-drk-norm dark:text-fg-lit-norm py1 px2 rounded shadow-sm',
    'text-h3': 'text-3xl font-semibold tracking-wider',
    'text-h4': 'text-xl font-semibold tracking-wider',
    'text-h5': 'text-lg font-semibold tracking-wider',
    'text-norm': 'text-fg-lit-norm dark:text-fg-drk-norm',
    'text-subtle': 'text-fg-lit-subtle dark:text-fg-drk-subtle',
    'text-muted': 'text-fg-lit-muted dark:text-fg-drk-muted',
    'text-flip': 'text-fg-drk-norm dark:text-fg-lit-norm',
  },
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
    presetWebFonts({
      provider: 'google',
      fonts: {
        sans: 'Titillium Web',
        mono: 'Fira Code',
      },
    }),
  ],
  theme: {
    borderRadius: {
      DEFAULT: '.125rem',
    },
    colors: {
      bgDrkA: '#18181B',
      bgDrkB: '#373737',
      bgDrkC: '#505050',
      bgDrkD: '#A1A1AA',
      bgDrkF: '#1D1D1D',
      bgDrkG: '#111111',
      bgDrkK: '#0B0B0B',
      bgLitA: '#FAFAFA',
      bgLitB: '#f4f4f5',
      bgLitC: '#e4e4e7',
      bgLitD: '#d4d4d8',
      bgLitF: '#a1a1aa',
      fgLitNorm: '#18181b',
      fgLitMuted: '#3f3f46',
      fgLitSubtle: '#71717a',
      fgDrkNorm: '#F9F9F9',
      fgDrkMuted: '#D4D4D4',
      fgDrkSubtle: '#A4A4A4',
    },
    fontFamily: {
      sans: 'Titillium Web',
      mono: 'Fira Code',
    },
    gridTemplateColumns: {
      workorderTable: '50px 20px 100px 150px auto 100px',
    },
  },
  safelist: ['bg-blue-500/80', 'shadow-blue-500/50',
    'bg-green-500/80', 'shadow-green-500/50',
    'bg-green-500/80', 'shadow-green-500/50',
    'bg-bg-drk-c/50', 'shadow-bg-drk-c-/50',
    'bg-orange-500/80', 'shadow-orange-500/50',
    'bg-orange-500/80', 'shadow-orange-500/50',
    'bg-bg-drk-c', 'shadow-bg-drk-c',
    'bg-red-500/80', 'shadow-red-500/50',
    'bg-yellow-500/80', '', 'hadow-yellow-500/50'],
  // transformers: [
  //   transformerDirectives(),
  //   transformerVariantGroup(),
  // ],
})

